/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    { pattern: /^bg-/, type: "class" },
    {
      pattern:
        /bg-(dancec|dramaticsc|egamingc|fashionc|fineartsc|literaryc|musicc|photographyc|quizc|shauryac|specialeventsc|day0c|day1c|day2c|day3c)/,
      type: "class",
    },
  ],
  theme: {
    extend: {
      colors: {
        primary: "#001233",
        secondary: "#002855",
        tertiary: "#023e7d",
        quaternary: "#0466c8",
        signinc: "#e3f4d7ff",
        eventc: "#aade87ff",
        schedulec: "#fff6d5ff",
        profilec: "#e6e6e6ff",
        contactc: "#ffd5d5ff",
        rulebookc: "#afc6e9ff",
        dancec: "#ffd5e5ff",
        dramaticsc: "#d5e5ffff",
        egamingc: "#eeaaffff",
        fashionc: "#ffe6d5ff",
        fineartsc: "#d5f6ffff",
        literaryc: "#f6ffd5ff",
        musicc: "#fffae3ff",
        photographyc: "#ccaaffff",
        quizc: "#d5fff6ff",
        shauryac: "#ffd5d5ff",
        specialeventsc: "#ffe4f9ff",
        day0c: "#e3f4d7ff",
        day1c: "#aade87ff",
        day2c: "#fff6d5ff",
        day3c: "#e6e6e6ff",
      },
      height: (theme) => ({
        "screen/90": "90vh",
        "screen3/4": "75vh",
        "screen/2": "50vh",
        "screen/3": "calc(100vh / 3)",
        "screen/4": "25vh",
        "screen/5": "20vh",
      }),
      backgroundImage: {
        signin: "url('./Assets/reg.png')",
        events: "url('./Assets/events.png')",
        schedule: "url('./Assets/schedule.png')",
        contact: "url('./Assets/contact.png')",
        profile: "url('./Assets/prof.png')",
        contactus: "url('./Assets/contactus.png')",
        rulebook: "url('./Assets/rule.png')",
        dance: "url('./Assets/Events/DANCE.png')",
        dramatics: "url('./Assets/Events/DRAMA.png')",
        egaming: "url('./Assets/Events/GAMING.png')",
        fashion: "url('./Assets/Events/FASHION.png')",
        finearts: "url('./Assets/Events/FINEARTS.png')",
        literary: "url('./Assets/Events/LITERARY.png')",
        music: "url('./Assets/Events/MUSIC.png')",
        photography: "url('./Assets/Events/PHOTOGRAPHY.png')",
        quiz: "url('./Assets/Events/QUIZ.png')",
        shaurya: "url('./Assets/Events/SHAURYA.png')",
        specialevents: "url('./Assets/Events/SPECIAL.png')",
        day0: "url('./Assets/Schedule/1bg.png')",
        day1: "url('./Assets/Schedule/1bg.png')",
        day2: "url('./Assets/Schedule/1bg.png')",
        day3: "url('./Assets/Schedule/1bg.png')",
      },
    },
  },
  plugins: [],
};
